#! /bin/bash
# Kathy Daniels
# 404887687
# find-missing-utf-8-header

export LC_ALL=en_US.utf8

# find and store UTF-8 file names into variable
FILES=`find $@ -type f -exec grep -Pl "[^\x01-\x7F]" '{}' +`

# separate elements of array with newline
# character to differentiate file arguments
IFS=$'\n'

# input files into an array
declare -a FILE_ARGS
let num=0

for i in $FILES
do
    FILE_ARGS[$num]=$i
    let num=$num+1
done

# for each file in the array, 
# find and store those that do NOT contain the header
for i in "${FILE_ARGS[@]}"
do
    FIRST_LINE=`head -n1 $i | grep -x "^-\*- coding: utf-8 -\*-$"`
    if [[ $FIRST_LINE == "" ]]
    then
	echo $i
    fi
done
