#! /bin/bash
# Kathy Daniels
# 404887687
# find-extra-utf-8-header

export LC_ALL='C'

# find and store ASCII file names into variable
FILES=`find $@ -type f -exec grep -PL "[^\x01-\x7F]" '{}' +`

# separates elements of array with newline
# character to differentiate file arguments
IFS=$'\n'

# use loop to put files into an array                                       
declare -a FILE_ARGS

let num=0

for i in $FILES
do
    FILE_ARGS[$num]=$i
    let num=$num+1
done

# for each file in the array, find and print those that contain the header
for i in "${FILE_ARGS[@]}"
do
    FIRST_LINE=`head -n1 $i | grep -x "^-\*- coding: utf-8 -\*-$"`
    if [[ $FIRST_LINE == "-*- coding: utf-8 -*-" ]]
    then
        echo $i
    fi
done
